[Variables]
Total=11
LastOpen=4

Name1=This PC
Icon1=PC.png
Cover1=PC.jpg
Dir1=shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

Name2=Firefox
Icon2=firefox.png
Dir2=C:\Program Files\Mozilla Firefox\firefox.exe
Cover2=firefox.jpg

Name3=Steam Big Picture
Icon3=steam.png
Dir3="C:\Program Files (x86)\Steam\Steam.exe" "-bigpicture"
Cover3=steam.jpg

Name4=Flashpoint
Icon4=flashpoint.png
Cover4=flashpoint.jpg
Dir4=F:\Emulator\Flashpoint\Start Flashpoint.lnk

Name5=Chrome
Icon5=chrome.png
Cover5=chrome.jpg
Dir5=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

Name6=After Effect
Icon6=ae.png
Cover6=ae.png
Dir6=F:\Program Files\Adobe After Effects CC 2015\Support Files\AfterFX.exe

Name7=Photoshop
Icon7=ps.png
Cover7=ps.jpg
Dir7=F:\Program Files\Adobe Photoshop CC 2015\Photoshop.exe

Name8=Discord
Icon8=discord.png
Cover8=discord.jpg
Dir8=C:\Users\siegw\AppData\Local\Discord\Update.exe" "--processStart" "Discord.exe

Name9=Photos
Icon9=Photo.png
Cover9=Photo.jpg
Dir9=shell:appsFolder\Microsoft.Windows.Photos_8wekyb3d8bbwe!App

Name10=My office
Icon10=office.png
Cover10=office.jpg
Dir10=shell:appsFolder\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe!Microsoft.MicrosoftOfficeHub

Name11=Setting
Icon11=setting.png
Cover11=setting.jpg
Dir11=ms-settings:

Name12=
Icon12=
Cover12=
Dir12=

Name13=
Icon13=
Cover13=
Background13=
Dir13=


Name15=
Icon15=
Cover15=
Background15=
Dir15=

Background1=
Background11=
Background12=
Background10=
Background9=
Background7=
Background6=
Background5=
Background4=
Background3=
Background2=
Background8=
Name14=
Icon14=
Cover14=
Background14=
Dir14=
