[Variables]
Total=19

Name1=IntelliJ 
Icon1=idea.png
Cover1=idea.png
Dir1=D:\IntelliJ IDEA\IntelliJ IDEA 2022.2.1\bin\idea64.exe
Background1=idea.png

Name2=VS Code
Icon2=vsicon.webp
Dir2=C:\Users\ahami\AppData\Local\Programs\Microsoft VS Code\Code.exe
Cover2=vscode.jpg
Background2=vscode.jpg

Name3=Sky
Icon3=skylogo.webp
Dir3=steam://rungameid/2325290
Cover3=sky.jpg
Background3=sky.jpg

Name4=Astroneer
Icon4=Icon_Astroneer.webp
Cover4=astroneer.jpg
Dir4=steam://rungameid/361420
Background4=astroneer.jpg

Name5=Minecraft
Icon5=Minecraft.png
Cover5=minecraft.png
Dir5=C:\Users\ahami\Desktop\Minecraft Launcher.lnk
Background5=minecraft.jpg

Name6=Factorio
Icon6=factorio_93863.webp
Cover6=factorio.jpg
Dir6=steam://rungameid/427520
Background6=factorio1.jpg

Name7=BONELAB
Icon7=BONELABicon.png
Cover7=boneworksbackground.jpg
Dir7=steam://rungameid/1592190
Background7=boneworksbackground.jpg

Name8=No Man's Sky
Icon8=nms.webp
Cover8=nms.jpg
Dir8=steam://rungameid/275850
Background8=nms2.jpg

Name9=Terraria
Icon9=terraria.png
Cover9=terrariacaves.jpg
Dir9=steam://rungameid/105600
Background9=terrariacaves.jpg

Name10=Apex Legends
Icon10=apex-legends.webp
Cover10=revvy.jpg
Dir10=steam://rungameid/1172470
Background10=revvy.jpg


Name11=Risk of Rain 2
Icon11=ror22.webp
Cover11=risk-of-rain-2.jpg
Background11=ror2.png
Dir11=steam://rungameid/632360


Name12=Sea of Thieves
Icon12=sot.webp
Cover12=sotwallpaper.jpg
Dir12=steam://rungameid/1172620
Background12=sotwallpaper.jpg

Name13=Warframe
Icon13=warframe.png
Cover13=warframe.jpg
Background13=warframe1.jpg
Dir13=steam://rungameid/230410

Name14=Payday 2
Icon14=Payday.ico
Cover14=payday2.jpg
Background14=payday2.jpg
Dir14=steam://rungameid/218620

Name15=Phasmophobia
Icon15=P.png
Cover15=phasmo.jpg
Background15=phasmo.jpg
Dir15=steam://rungameid/739630

Name16=Satisfactory
Icon16=satisfactory.png
Cover16=satisfactory.jpg
Background16=satisfactory.jpg
Dir16=

Name17=Neos
Icon17=Neos.png
Cover17=NeosMoon.jpg
Background17=NeosPromo1080.png
Dir17=D:\Neos\NeosProLauncher.exe

Name18=Beat Saber
Icon18=BeatsaberIcon.webp
Cover18=beatsaber.jpg
Background18=beatsaber.jpg
Dir18=steam://rungameid/620980

Name19=ARK
Icon19=Pteranodon.webp
Cover19=ark.jpg
Background19=ark.jpg
Dir19=steam://rungameid/346110
LastOpen=3
