[Variables]
Title=Applications
TotalGame=3
Directory=#@#App\

Gamecover1=code.png
Gamedir1=submenu:SubdockIDE
Gamename1=IDEs

Gamecover2=setting.png
Gamedir2=submenu:SubdockSetting
Gamename2=Settings
;Background2=Steam.jpg

Gamecover3=photoshop.png
Gamedir3=["C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Photoshop 2023.lnk"]
Gamename3=Photoshop

Gamecover4=photoshop.png
Gamedir4=["D:\Program Files\Adobe Photoshop CC 2015\Photoshop.exe"]
Gamename4=Photoshop
