[Variables]
Title=Bookmarks
TotalGame=8
Directory=#@#App\

Gamecover1=canvas.png
Gamedir1=https://sandiegounified.instructure.com/courses/215960
Gamename1=Schools

Gamecover2=youtube.png
Gamedir2=https://www.youtube.com
Gamename2=Youtube

Gamecover3=github.png
Gamedir3=https://github.com/
Gamename3=GitHub

Gamecover4=twitch.png
Gamedir4=https://gaming.amazon.com/home
Gamename4=Twitch Prime

Gamecover5=gmail
Gamedir5=https://mail.google.com/
Gamename5=Gmail

Gamecover6=reddit.png
Gamedir6=https://www.reddit.com/
Gamename6=Reddit

Gamecover7=unnamed.png
Gamename7=Translate
Gamedir7=https://translate.google.com/

Gamecover8=spotify.png
Gamename8=Spotify
Gamedir8=https://open.spotify.com/
