[Variables]
Title=IDEs
TotalGame=5
Directory=#@#App\

Gamecover1=idea colored.png
Gamedir1=["C:\Users\Public\Desktop\IntelliJ.lnk"]
Gamename1=IntelliJ

Gamecover2=vs-insider.png
Gamedir2=["C:\Users\ahami\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Visual Studio Code - Insiders\Visual Studio Code - Insiders.lnk"]
Gamename2=Visual Studio - Insiders

Gamecover3=vs-code.png
Gamedir3=C:\Users\ahami\AppData\Local\Programs\Microsoft VS Code\Code.exe
Gamename3=VS Code

Gamecover4=github.png
Gamedir4=https://github.com/galexy727
Gamename4=GitHub
Gamecover5=BlueJ.png
Gamedir5=["C:\Users\ahami\Desktop\BlueJ.lnk"]
Gamename5=BlueJ
