[Variables]
TotalGame=7
Directory=#@#App\

Gamecover1=explorer.png
Gamedir1=submenu:SubdockExplorer
Gamename1=Explorer
;Background1=file.jpg

Gamecover2=power.png
Gamedir2=submenu:PowerMenu
Gamename2=Power
;Background2=windows.jpg

Gamecover3=app.png
Gamedir3=submenu:SubdockApp
Gamename3=Apps
;Background3=apps.jpg

Gamecover4=trashbin.png
Gamedir4=function:trashbin
Gamename4=Recycle Bin

Gamecover5=bookmark.png
Gamedir5=submenu:Subdock
Gamename5=Bookmarks
;Background5=web.jpg

Gamecover6=controller.png
Gamedir6=gamehub:page_game.inc
Gamename6=Games
;Background6=games.jpg

Gamecover7=G.I. Rob.png
Gamedir7=submenu:SubdockRobot
Gamename7=Robotics
