[Variables]
Title=FRC
TotalGame=3
Directory=#@#App\

Gamecover1=wpi.png
Gamedir1=["C:\Users\ahami\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\2024 WPILib VS Code.lnk"]
Gamename1=WPILib

Gamecover2=pathplanner.png
Gamedir2=["C:\Users\ahami\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\PathPlanner.lnk"]
Gamename2=PathPlanner

Gamecover3=tba.png
Gamedir3=["C:\ProgramData\Microsoft\Windows\Start Menu\Programs\FRC Driver Station.lnk"]
Gamename3=DriverStation