[Background1] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background2] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background3] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background4] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background5] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background6] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background7] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background8] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background9] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background10] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background11] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background12] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background13] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background14] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background15] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background16] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background17] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background18] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Background19] 
Meter=Image 
MeterStyle=Background
ImageName=
Hidden=0

[Icon1] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(1)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(1)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(1)"]
ImageName=#@#Icons\#Icon1#
Hidden=0

[Icon2] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(2)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(2)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(2)"]
ImageName=#@#Icons\#Icon2#
Hidden=0

[Icon3] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(3)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(3)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(3)"]
ImageName=#@#Icons\#Icon3#
Hidden=0

[Icon4] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(4)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(4)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(4)"]
ImageName=#@#Icons\#Icon4#
Hidden=0

[Icon5] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(5)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(5)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(5)"]
ImageName=#@#Icons\#Icon5#
Hidden=0

[Icon6] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(6)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(6)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(6)"]
ImageName=#@#Icons\#Icon6#
Hidden=0

[Icon7] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(7)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(7)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(7)"]
ImageName=#@#Icons\#Icon7#
Hidden=0

[Icon8] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(8)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(8)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(8)"]
ImageName=#@#Icons\#Icon8#
Hidden=0

[Icon9] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(9)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(9)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(9)"]
ImageName=#@#Icons\#Icon9#
Hidden=0

[Icon10] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(10)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(10)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(10)"]
ImageName=#@#Icons\#Icon10#
Hidden=0

[Icon11] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(11)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(11)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(11)"]
ImageName=#@#Icons\#Icon11#
Hidden=0

[Icon12] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(12)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(12)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(12)"]
ImageName=#@#Icons\#Icon12#
Hidden=0

[Icon13] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(13)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(13)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(13)"]
ImageName=#@#Icons\#Icon13#
Hidden=0

[Icon14] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(14)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(14)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(14)"]
ImageName=#@#Icons\#Icon14#
Hidden=0

[Icon15] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(15)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(15)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(15)"]
ImageName=#@#Icons\#Icon15#
Hidden=0

[Icon16] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(16)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(16)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(16)"]
ImageName=#@#Icons\#Icon16#
Hidden=0

[Icon17] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(17)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(17)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(17)"]
ImageName=#@#Icons\#Icon17#
Hidden=0

[Icon18] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(18)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(18)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(18)"]
ImageName=#@#Icons\#Icon18#
Hidden=0

[Icon19] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(19)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(19)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(19)"]
ImageName=#@#Icons\#Icon19#
Hidden=0