[Variables]

size=50
;icon size

;background=29, 42, 64
;Background color, delete this line remove background

;background_width=60

update_rate=10
;Redraw delay (framerate delay)

padding=20
;increase to make icon smaller

focus=0
;Whether to hide icons when a submenu is open
snap=1
;Whether to snap sub-menu position to dock (when focus is false)

move_file=1
;Whether to move file instead of copy when drag and drop file in

direction=1
;direction of the skin, 1:up  2:down  3:left  4:right

FontColor=255,255,255
FontSize=12
TextY=10
TextW=0
TextBackground=0,0,0
;Color and size icon name
